### ISSUE TITLE
KvAdaptaDark. Backspace arrow icon is stretched in text input fields.

### ISSUE THREAD

**Issue by varlesh** [tsujan/Kvantum#172]
If set font more 11px (12px) - icons stretched on Lineedit widget
![image](https://user-images.githubusercontent.com/8083855/34663542-cd838f30-f470-11e7-847a-722024ab700b.png)

More info here:
https://github.com/PapirusDevelopmentTeam/adapta-kde/issues/33

**Comment by varlesh** [comment]
Reproduced on KvAdaptaDark & KvAdapta themes.
Kvantum 0.10.5

**Comment by varlesh** [comment]
@tsujan Why icon use text font size? It's very strange...

**Comment by varlesh** [comment]
**For compare screens.**
Font Noto Sans 10:
![image](https://user-images.githubusercontent.com/8083855/34663715-8c3b4490-f471-11e7-8fef-5e3273e1402a.png)
Font Noto Sans 12:
![image](https://user-images.githubusercontent.com/8083855/34663733-a815a3ea-f471-11e7-9091-b1c5118a38d0.png)

**Comment by tsujan** [comment]
I've seen that only under KDE, never under LXQt. I think, somehow, KDE's Qt plugin interferes with sizes.

**Comment by tsujan** [comment]
This is under LXQt and with a relatively big font:

![lxqt](https://user-images.githubusercontent.com/981076/34667694-5efd7a8a-f47f-11e7-9935-d0d637b59945.png)

As you see, everything is OK.

Why KDE does that, I still don't know but will try to find out.

**Comment by varlesh** [comment]
hm... interesting. 
With Breeze engine set font 12px or even 14px this not reproduced...
Also on my kvantum theme Arc/Arc Dark this not reproduced too. But reproduced on your KvArc/KvArcDark

**Comment by varlesh** [comment]
It's happend with option minimal size on `[PanelButtonCommand]`:
```
min_width=+0.3font
min_height=+0.3font
```

**Comment by tsujan** [comment]
@varlesh The height of that ugly big icon is apparently not 0.3 × font height. Other style engines don't have the concept of `min_width`. Something is very wrong with KDE.

I saw this issue months ago but didn't report it to KDE developers because I didn't have time to explain to them how Kvantum worked and how KDE interfered with it. Actually, the fact that this issue didn't exist before shows that it's a KDE problem.

All what I might be able to do is searching for a workaround... but no promise.

**Comment by tsujan** [comment]
There's yet another possibility: fonts like Noto Sans have a bug. Does it happen with Dejavu Sans, for example?

**Comment by tsujan** [comment]
> I'm remove this min_width min_height and this solve problem

No, don't do that! I think I found a workaround.

And please answer my last question: Does it happen with Dejavu Sans?

**Comment by varlesh** [comment]
Yes, but another size - 14px Dejavu Sans Regular

**Comment by varlesh** [comment]
![image](https://user-images.githubusercontent.com/8083855/34668742-28fb2d0c-f488-11e7-8ac7-ebc4c17b5390.png)

**Comment by tsujan** [comment]
OK, thanks! I'll tell you whenever I find a good solution. Don't touch your theme!

**Comment by varlesh** [comment]
i'm already commited ))
https://github.com/PapirusDevelopmentTeam/adapta-kde/commit/f0a181e94ab16f8aee59c0bb3659974c796b006a

**Comment by varlesh** [comment]
If you find solution, i'm revert commit...

**Comment by tsujan** [comment]
> i'm already commited ))

You'll reverse it later ;)

**Comment by tsujan** [comment]
Ha ha, found the son of a.... It's *Qt bug* and happens with Fusion too. The following screenshot is taken with Fusion and Noto Sans 14:

![fusion](https://user-images.githubusercontent.com/981076/34670721-d022d388-f48c-11e7-9459-d34b447bf0e2.png)

Breeze has a workaround for it, somehow. I should really find a workaround for it for Kvantum.

**Comment by tsujan** [comment]
Fixed in https://github.com/tsujan/Kvantum/commit/3fc4229a195a9626bf63066b88dc7eb433c8d1cc. Now, the icon is sharp even with ridiculously huge fonts (open the screenshot in a new tab to see how big the fonts are):

![huge](https://user-images.githubusercontent.com/981076/34673923-3578b502-f499-11e7-915e-98b9fe74c125.png)

As always, thank you for reporting such issues! Please keep doing so.

Please close this issue after you confirmed it's fixed.

**Comment by tsujan** [comment]
I reported it at https://bugreports.qt.io/browse/QTBUG-65627. However, Qt5 developers may not fix serious bugs (there are some with high priority but not fixed for years), let alone this bug.

**Comment by cross1983** [comment]
I have just updated kvantum-qt5-git from AUR and have checked KvAdaptaDark theme. 
Issue still happens.

![image](https://user-images.githubusercontent.com/17809174/34676321-7e830faa-f49d-11e7-9f12-f13dd76a9f09.png)

**Comment by varlesh** [comment]
@cross1983 Thx for testing. 
@tsujan I'm use deb-based distro and don't not have opportunity use git-version (need rebuild packages)

**Comment by tsujan** [comment]
@cross1983 I think there should be a problem with your recompilation. Please get the latest git source directly from here and do:
```
qmake && make
[let the program be compiled and then:]
sudo make install
```

**Comment by cross1983** [comment]
@tsujan, 
Now issue is solved

![image](https://user-images.githubusercontent.com/17809174/34679261-7d1bf88a-f4a6-11e7-99f1-5d901ed03281.png)

**Comment by tsujan** [comment]
@cross1983 Thanks for the confirmation! Strange that the Arch git `PKGBUILD` doesn't get the latest source!

If you want to use Arch git packages again later, don't forget that you should use the `--force` option with pacman for the files to be overwritten.

Closing this.

**Comment by cross1983** [comment]
I have checked clean install from AUR. Now all is OK.
