### ISSUE TITLE
Tooltips padding without compositing

### ISSUE THREAD

**Issue by franksouza183** [tsujan/Kvantum#22]
The same problem occurred with the popup menus (https://github.com/tsujan/Kvantum/issues/20, already solved) also seems to occur with tooltips without compositing, it uses the default of 2px.
![Kvantum print](http://i.imgur.com/zCkKG7S.jpg)
I tried to set a [Tooltip] group, but it seems ignore. Is there any specific configuration for tooltips related to frame.top/bottom/left/right?
Note: the padding that I seek should work on all sides (top, bottom, left and right)

**Comment by tsujan** [comment]
Yes, I'd put the same 2-px limit on tooltips without compositing and forgot to remove it. I'll fix it soon.

**Comment by tsujan** [comment]
Should be fixed now.

Unlike menus, a tooltip can only have the same thickness for all of its frames. It is the maximum of the four frame widths under the ToolTip section.

Some rare tooltips, like those in KDE System Settings, have hard-coded frame widths.

**Comment by franksouza183** [comment]
Ok, trying now

**Comment by franksouza183** [comment]
I think it still have some problems in the corners:
![Kvantum print](http://i.imgur.com/tGoE0J3.jpg)

Tooltip section:

`[Tooltip]
frame.top=10
frame.bottom=10
frame.left=10
frame.right=10`

**Comment by tsujan** [comment]
I'm afraid it should be ToolTip, not Tooltip. And are you sure your svg elements for tooltip corners are OK?

**Comment by franksouza183** [comment]
I tried with 'ToolTip` too, here is the theme: http://franksouza.com.br/EvolvereLight.zip

**Comment by tsujan** [comment]
I'll check it and tell you soon.

**Comment by tsujan** [comment]
Oh, it was just an error in the blue corner images! I changed 8 nodes of your tooltip blue border to corners (with Inkscape) and the problem was fixed. Here is the modified svg: https://dl.dropboxusercontent.com/u/7793460/EvolvereLight.svg

Your theme still needs some work but it's really elegant. Congratulations!

**Comment by tsujan** [comment]
I also recommend you use a more distinguishable interior/frames for toggled buttons because their toggled state can't be easily seen now.

**Comment by franksouza183** [comment]
Wow, I apologize for making you waste time like this. I'll take more care next time about it. And yes, this issue still needs some tweaking.

Many many thanks for the correction in the code for the compliment, and for help with the svg!

You can close the issue if you want;)

**Comment by tsujan** [comment]
No problem at all! Finding that svg error was a challenge. Such errors occur infrequently but when they do, they can't be seen with eyes ;)
