### ISSUE TITLE
update to 0.12.1 breaks window transparency with hidpi

### ISSUE THREAD

**Issue by scarwire** [tsujan/Kvantum#445]
Hi there,

I have hidpi screen scaling set to 1.5x in KDE (Plasma 5.16.15, Qt 5.13.1), and I noticed that the update from Kvantum 0.11.2 to 0.12.1 breaks window background transparency/translucency.

Steps to reproduce:

1. Create a new user in kde. The display scaling should be automatically be set to 1x.
2. Select kvantum application style
3. In Kvantum manager, choose a theme that uses background transparency (for example KvRoughGlass or Canta-dark). New windows will apply the style correctly with a translucent background.
4. Go to display preferences, set scaling to 1.5x.
5. Log out and log back in. New windows will apply the kvantum style but there will be no background transparency.

In 0.11.2, there were already a few other bugs with hidpi scaling. Artifacts like these: ![screenshot](https://user-images.githubusercontent.com/33032008/67217851-b211f780-f425-11e9-83a9-874d4630fefe.png)

However I'm guessing these kinds of bugs might be from [upstream](https://bugreports.qt.io/browse/QTBUG-53022) and will be sorted out in future versions of Qt.

Thanks!

**Comment by tsujan** [comment]
Window translucency is disabled with non-integer scale factors intentionally. The reason is that Qt's support for non-integer scale factors is a mess: even Fusion shows artifacts. The artifacts would become intolerable with translucency (Qt 5.13 has had the worst situation until now).

Window translucency is functional with integer scale factors though.

> In 0.11.2, there were already a few other bugs with hidpi scaling. Artifacts like these...

That's a Qt bug; nothing has changed in Kvantum regarding scaling (except for disabling translucency with non-integer factors).

Also see https://github.com/tsujan/Kvantum/issues/431. Apparently, both KDE and Qt has had serious regressions.

**Comment by tsujan** [comment]
BTW, I'll enable window translucency with non-integer scale factors again as soon as Qt bugs are fixed but I'm not optimistic after seeing so many new bugs in Qt 5.13 (they aren't limited to the current topic).

**Comment by tsujan** [comment]
Update:

With Qt 5.14.0 and when there is no translucency, most artifacts — if not all — are fixed. But, with translucency there are still bad artifacts.

**Comment by Thaodan** [comment]
![Screenshot_20200112_221551](https://user-images.githubusercontent.com/1747359/72225731-22459a80-3589-11ea-9332-57b362592568.png)
Doesn't look that bad for me.
Maybe it depends on the graphics stack?

**Comment by tsujan** [comment]
> Maybe it depends on the graphics stack?

Improbable because the integer scaling factors work (and have worked) without problem. You need to play with this or that widget or use various themes to see the problem. Yes, it's better than before (as I said in the comment) but it's still buggy.

**Comment by jurienhamaker** [comment]
Is it possible to still enable this manually? Using latest git aut

**Comment by tsujan** [comment]
> Is it possible to still enable this manually?

No. As far as possible, I really don't want Kvantum to inherit Qt's bugs -- had a lot of trouble to do so with Qt 5.14, for example.

**Comment by cartilage-ftw** [comment]
Itʻs been over a year and the issue still exists, Dolphin isnʻt translucent in fractional scaling. I have to use 1.25x due to my display size but I love transparency too :(

Iʻm using the latest release of Manjaro KDE Plasma

![Dolphin still not translucent](https://i.imgur.com/CyczOME.png)

**Comment by tsujan** [comment]
@cartilage-ftw
This is an old info now: `Kvantum Manager → Hacks → Disable translucency with non-integer scaling`. Make sure you read the warning message!

If you don't see it, your Kvantum installation is outdated. The latest release is 0.17.0.

**Comment by cartilage-ftw** [comment]
@tsujan aha, thank you so much! Iʻll switch that disable option back on if I encounter any problems :). 

![Fixed :)](https://i.imgur.com/PeptFI8.png)

**Comment by tsujan** [comment]
> Iʻll switch that disable option back on if I encounter any problems

Most probably, you'll see artifacts in some places. Whether they'll be tolerable or not, I don't know. Qt 5.15 has become much better in this regard but the bug still exists.
