### ISSUE TITLE
treeview color issue in qelectrotech

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#58]
not sure if this is an issue with my theme but it makes the the elements browser unusable
![screen](https://cloud.githubusercontent.com/assets/3780774/11015424/1767b424-855f-11e5-8682-a44ece0cb83a.png)

**Comment by sixsixfive** [comment]
also short question ;) is it possible to set a different color(eg a bit darker) for docked docks?

**Comment by tsujan** [comment]
If there isn't such a color gradient in your theme, it should be a design flaw in the app: it sets that gradient but not the text color. Have you seen this anywhere else?

As far as I know, QStyle has nothing for dock's bg color; it takes its bg from the widget behind it.

**Comment by tsujan** [comment]
In fact, the text color issue is a result of Kvantum trying to **avoid** such problems (and it does in most cases). Here, the bg brush is set to a dark color, while the gradient is light. Let me see if it's possible to work around such cases too!

**Comment by tsujan** [comment]
Done! Now it's your responsibility to check for any side-effect for other custom bg view-items ;) Please test kSysGuard (select some of its rows), konsole > profile editing > appearance > edit, or any other app that you know has view-items with hard-coded bg (I have no access to KDE right now).

**Comment by sixsixfive** [comment]
ok its better now but i still cant see which category is currently selected

breeze: category is hightlighted:
![screen png](https://cloud.githubusercontent.com/assets/3780774/11021771/cdf541aa-864c-11e5-8c97-4ca8ea293515.jpg)
kvglare: nothing ;(
![screen2 png](https://cloud.githubusercontent.com/assets/3780774/11021772/d2e05038-864c-11e5-93fb-a8958ccea019.jpg)
kvdefault: only borders (i guess my theme has no borders which is the reason why i see nothing...
![screen3 png](https://cloud.githubusercontent.com/assets/3780774/11021773/d65dbca0-864c-11e5-9130-2e28f4b424a2.jpg)

also i tested ksysguard and konsole(i have only qt5 kde apps installed)

ksysguard looks ok, konsole has a minor issue (the round border of selected items is removed/fully highlighted)

![screen4](https://cloud.githubusercontent.com/assets/3780774/11021799/7084c94a-864d-11e5-98bb-17ee4619dd5c.png)

**Comment by tsujan** [comment]
Thanks for testing!

Konsole is all right: that's the best possible compromise between custom bg's and Kvantum's SVG bg's. Nothing's changed by the last commit.

The same is true for selected qelectrotech's view-items. Kvantum respects the hard-coded gradient and finds an appropriate text color; Breeze doesn't. Kvantum tries to compensate for the design flaw with the border color.

Working around design flaws has been one of the difficult tasks I've had in developing Kvantum. Someone makes an app, adds some incomplete hard-coded style, sees it under the default theme and thinks everything is OK. "The best possible compromise" couldn't be perfect, of course.

**Comment by sixsixfive** [comment]
ok i think its done then
