### ISSUE TITLE
Bottom part of most Qt windows are not blurred and fully transparent

### ISSUE THREAD

**Issue by thakurnp** [tsujan/Kvantum#946]
Kvantum Manager 1.1.0 (Built from git)

Operating System: KDE neon 6.0
KDE Plasma Version: 6.0.0
KDE Frameworks Version: 6.0.0
Qt Version: 6.6.2
Kernel Version: 6.5.0-21-generic (64-bit)
Graphics Platform: Wayland

![Screenshot_20240304_170002](https://github.com/tsujan/Kvantum/assets/53616404/88b5e556-1f11-4e1d-829c-8b3bd04a1203)

**Comment by tsujan** [comment]
Do you use a scale factor > -1? See https://github.com/tsujan/Kvantum/issues/943#issuecomment-1975191017

**Comment by thakurnp** [comment]
In my case scale is 1 i.e. 100%

![Screenshot_20240304_183712](https://github.com/tsujan/Kvantum/assets/53616404/8b5c88e3-fd9d-4434-b9a6-a4fcad28ca43)

Hope it helps

and Thanks for Kvantum

**Comment by tsujan** [comment]
Which Kvantum theme do you use (please give me a link for downloading it)? Does it happen with all themes?

**Comment by SlamZDank** [comment]
This bug also happens on my end, haven't tested with other themes.
I used this one [https://www.pling.com/p/1499836/](url)
I Hope this helps!

**Comment by tsujan** [comment]
The theme is OK.

I checked with kwin_wayland V5 and systemsettings5 and there was no problem. Also, there's no problem with any Qt6 app. So, most probably, this is about a bug in Neon.

As in the case of https://github.com/tsujan/Kvantum/issues/945, I can't say anything with certainty before a stable version of Plasma6 comes here. Will keep this open until then.

**Comment by SlamZDank** [comment]
Apparently what we were experiencing was a result of this [kwin bug](https://bugs.kde.org/show_bug.cgi?id=482294) that was dealt with with the release of plasma 6.0.1.

Thanks for the support!

**Comment by tsujan** [comment]
@SlamZDank
Thanks for the info!

**Comment by thakurnp** [comment]
Upgraded to plasma 6.0.2 today, issue is resolved in this update.

**Comment by duncanyoyo1** [comment]
I still have this issue on Plasma 6.0.2, not sure what is causing it.

**Comment by tsujan** [comment]
> I still have this issue on Plasma 6.0.2

Probably you don't have git Kvantum.

**Comment by duncanyoyo1** [comment]
That's probably it, I will try it now.

I am currently using 

```
extra/kvantum 1.0.10-3 (1.1 MiB 8.0 MiB) (Installed)
    SVG-based theme engine for Qt6 (including config tool and extra themes)
```
from the Arch repos https://archlinux.org/packages/extra/x86_64/kvantum/

Which says it's Qt6, so I thought it was updated for Plasma 6.

**Comment by tsujan** [comment]
> Which says it's Qt6

It is Qt6, but KF6 didn't exist when Kvantum 1.0.10 was released. The git Kvantum supports KF6 and so, Plasma6's blur effect.

**Comment by duncanyoyo1** [comment]
Thanks for the quick reply, and yeah that's totally on me for assuming it was updated.

Seems to be working fine now.

Thanks again!

**Comment by tsujan** [comment]
> ... assuming it was updated.

Technically, it is up-to-date because it's based on the latest release, not git. I'll release 1.1.0 when I can test git Kvantum completely under a really stable version of Plasma 6.

**Comment by tsujan** [comment]
I released [Kvantum 1.1.0](https://github.com/tsujan/Kvantum/releases/tag/V1.1.0). As far as I tested, menus of Plasma 6.0.2 were OK with it; hence closing this...
